#+TITLE: My Raspberry Pi 5 Homelab

* Introduction
In this repository I have listed all of the steps I have taken to configure my Raspberry Pi 5 for a homelab. This serves as documentation that I can get back to if I want to look something up, and hopefully it will be helpful to others too.

* Setup
+ *Device:* Raspberry Pi 5 Model B
+ *Memory:* 8GB RAM
+ *OS:* Debian GNU/Linux 13 (trixie) aarch64 --- /This is Pi OS Lite (64-bit) which comes with no desktop environment/
+ *Storage:* (Official) Raspberry Pi Flash Drive 256GB

* Prerequisites
** Docker
[[https://www.docker.com/][Docker]] is a free and open-source software that automates the deployment and running of containerized applications.

Installing Docker:
#+begin_src bash
curl -fsSL https://get.docker.com | sh
#+end_src

Testing docker for correct operation:
#+begin_src bash
sudo docker run --rm hello-world
#+end_src

Adding the user to the docker group:
#+begin_src bash
sudo usermod -aG docker <my-username> # where my-username is the username of your account
#+end_src

Then exit and log back in to be added to the docker group.

** Tailscale
[[https://tailscale.com/][Tailscale]] is a free and open-source VPN service that allows you to connect all your devices. The free plan supports up to 100 devices and 3 users.

Installing Tailscale:
#+begin_src bash
curl -fsSL https://tailscale.com/install.sh | sh
#+end_src

Starting Tailscale:
#+begin_src bash
sudo tailscale up
#+end_src

* Services
** Portainer
[[https://github.com/portainer/portainer][Portainer]] is a web app which allows you to easily organize and manage all your containers.

To install Portainer I followed this [[https://raspberrytips.com/portainer-on-raspberry-pi/][guide]].

Pulling the container:
#+begin_src bash
docker pull portainer/portainer-ce:latest
#+end_src

Starting Portainer using docker:
#+begin_src bash
sudo docker run -d -p 9000:9000 --name=portainer_app --restart=always -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data portainer/portainer-ce:latest
#+end_src

Then Portainer can be accessed at ~http://<my-hostname>:9000~, where my-hostname is the hostname of your Raspberry Pi.

** Nextcloud
[[https://nextcloud.com/][Nextcloud]] is a self-hosted productivity platform allowing you to sync your files, calendar, etc. Basically, it can replace the whole Google ecosystem (except the email service).

To install Nextcloud I followed this [[https://www.youtube.com/watch?v=CHWHQFwxFcE][guide]] on YouTube.

Pulling the container:
#+begin_src bash
docker pull nextcloud
#+end_src

Creating a docker network:
#+begin_src bash
docker network create --driver bridge nextcloud-net
#+end_src

Docker's default database is SQLite, but it is not recommended for extensive use. So, Postgres is used instead.

Starting the database (Postgres) container:
#+begin_src bash
docker run --name postgres -e POSTGRES_PASSWORD=<my-password> --network nextcloud-net -d postgres # where my-password is the password for the database
#+end_src

Running the Nextcloud container:
#+begin_src bash
docker run --name nextcloud -d -p 8080:80 -v /home/pi/nextcloud:/var/www/html --network nextcloud-net nextcloud
#+end_src

Nextcloud can be accessed at ~https://<my-hostname>:8080~, where you will be prompted to create an account.

For Data folder use ~/var/www/html/data~

Choose PostgreSQL for database and use ~postgres~ for username, database name, and container name.

Use the password that you configured for the database when you ran the container.

** Nextcloud Whiteboard
This is the official [[https://github.com/nextcloud/whiteboard][Whiteboard app]] for Nextcloud. It is an integration of [[https://github.com/excalidraw/excalidraw][Excalidraw]] into Nextcloud, and supports drawing, writing text, etc. on an infinite canvas featuring real-time collaboration. I have found it to be the best self-hosting solution for hand-written notes on iPad. The stylus support is excellent and the files are being updated instantly. There have been complaints that palm rejection on the iPad does not work so well, but I have not experienced any issues so far.

To install it I just followed the instructions on Whiteboard's [[https://github.com/excalidraw/excalidraw][Github]].

Running the container:
#+begin_src bash
docker run -d --name nextcloud-whiteboard -e JWT_SECRET_KEY=<some-random-secret> -e NEXTCLOUD_URL=http://<my-hostname>:8080 -p 3002:3002 --restart unless-stopped ghcr.io/nextcloud-releases/whiteboard:stable # where some-random-secret a password of your choice, it will be needed later
#+end_src

Once the container is up and running, you can create a new whiteboard by going to Files > New > New whiteboard.

You will notice there is a red WiFi icon on the bottom right indicating you are offline. Indeed, the file cannot be shared among other devices, because the WebSocket server has not been configured yet. In order to configure it, you go to Administration Settings > Administration (Section) > Whiteboard. There you need to fill in the following information:

*WebSocket URL:* ~http://<my-hotname>:3002~

*Shared Secret:* ~<some-random-secret>~

After saving the settings, you should see a confirmation message, and you are good to go!

** Bitwarden
[[https://bitwarden.com/][Bitwarden]] is a free and open-source password manager that allows you to store all of your passwords securely, and it is available on all platforms. Unfortunately, there is no official support for ARM-based server (yet). [[https://github.com/dani-garcia/vaultwarden][Vaultwarden]] is an alternative server implementation, which requires minimal resources, and it can easily be deployed on Raspberry Pi.

To install Vaultwarden I followed this [[https://raspberrytips.com/install-bitwarden-on-raspberry-pi/][guide]].

Pulling the container:
#+begin_src bash
docker pull vaultwarden/server:latest
#+end_src

Using Bitwarden/Vaultwarden requires HTTPS. So, I followed this [[https://www.xda-developers.com/enabled-https-secure-self-hosted-apps-tailscale/][guide]] to generate a free TLS Certificate using Tailscale. Note that the certificates are valid for 90 days.

First, enable HTTPS in the settings. This can be found in the DNS tab of the admin console.

Then, on the Raspberry Pi generate the certificate using the following command:
#+begin_src bash
sudo tailscale cert <machine-name>.<tailnet-name>.ts.net # machine-name is Raspberry's hostname by default, tailnet-name can be modified to make it easier to remember
#+end_src

You should see two files: ~.cert~ and ~.key~

Transfer the generated files to the ~/ssl/keys~ folder.

The Vaultwarden container can finally be deployed to support HTTPS, by passing the ~.key~ and ~.cert~ files to "Rocket":
#+begin_src bash
docker run -d -e ROCKET_TLS='{certs="/ssl/<machine-name>.<tailnet-name>.ts.net.cert",key="/ssl/<machine-name>.<tailnet-name>.ts.net.cert"}' -v /ssl/keys/:/ssl/ -v /vw-data/:/data/ -p 443:80 vaultwarden/server:latest
#+end_src

** FreshRSS
** Super Productivity
[[https://github.com/super-productivity/super-productivity][Super Productivity]] is a ToDo list app with time boxing and time tracking capabilities. ToDos can be organized through different tags and projects. It supports integration with Trello, GitHub, Azure DevOps, etc.

No special setup for setting up the container here; I just used portainer to pull and deploy the container using this [[https://hub.docker.com/r/johannesjo/super-productivity/tags][image]] (official).

Synchronization is possible with SuperSync (beta), Dropbox or Nextcloud. In this setup I used Nextcloud, but additional steps were required to allow super productivity to modify files.

In the first place, Super productivity needs permission to use WebDav. So, in the Administration Settings of Nextcloud, in the WebAppPassword section, SuperProducivity's URL needs to be added as an allowed origin for WebDav/CalDav requests.

Furthermore, configuring SuperProducivity Sync requires a separate app password (Nextcloud's won't work here). An app password can be generated in the Personal Settings of Nextcloud, in the Security section. Take note of the password, as it will be displayed only once. You can use the same password for all your devices.

Finally, make sure there is a folder in the root of your Nextcloud files having the same name as the Sync Folder Path you specified in the configuration. Super Producivity won't create the folder for you automatically.

* Backups
I am taking backups by creating snapshots using [[https://rsnapshot.org/][rsnapshot]]. This is a snapshot utility based on [[https://linux.die.net/man/1/rsync][rsync]], and it can be used to take periodic backups of local or remote machines over ssh. It is making use of hard links, in order to reduce disk space usage.

To configure rsnapshot I followed this [[https://raspberrytips.com/rsnapshot-raspberry-pi/][guide]].

Once rsnapshot is installed, it can be configured by editing ~/etc/rsnapshot.conf~.

The first step is to set the "root" directory, where the snapshots are going to be saved:
#+begin_src
snapshot_root /media/angel/raspberry_backups
#+end_src

In this case, I am using an external drive which has been mounted to ~/media/angel~.

The next step is to set the number of backups to keep per backup level. Here I have replaced the following lines
#+begin_src
retain    alpha    6
retain    beta     7
retain    gamma    4
#+end_src

with those:
#+begin_src
#retain    daily      7
retain    weekly     4
#retain    monthly    6
#+end_src

The daily, weekly, and monthly correspond to the levels of backup, while the numbers represent the number of snapshots that will be maintained before the first backup is replaced.

As you may notice, I have commented out the daily and weekly. For now I am getting my backups manually once a week, so there is no need for multiple levels.


Lastly, we can select the folders we want to backup:
#+begin_src
###############################
### BACKUP POINTS / SCRIPTS ###
###############################

# LOCALHOST
backup	/home/		localhost/
backup	/etc/		localhost/
backup	/usr/local/	localhost/
backup	/var/lib/	localhost/
backup	/opt/		localhost/
#+end_src

Once the necessary changes have been made, the configuration can be tested/validated using the following command:
#+begin_src bash
sudo rsnapshot configtest
#+end_src

If the output is "Syntax OK", it means the configuration does not have any syntax errors.

Before taking your first backup, you can verify that all permissions are configured correctly by running rsnapshot in dry-run mode:
#+begin_src bash
sudo rsnapshot -t daily
#+end_src

Finally, you can take backups by using the same command without the -t flag:
#+begin_src bash
sudo rsnapshot daily
#+end_src

The backups can be automated using [[https://en.wikipedia.org/wiki/Cron][Cron]]. I have not done this yet, but if you are interested in configuring it you can follow the guide I mentioned earlier.
